### ISSUE TITLE
Handle `char` parameters/locals properly

### ISSUE THREAD

**Issue by lynn** [lynn/chibicc#1]
Currently, everything on the working stack and the "stack frames" is 2 bytes, and a `char` is just stored as an `int` (by putting a `00` byte in front of it).

The problem with this is that in `void f(char a)`, accessing `a` implicitly involves dereferencing `&a`, which chibicc knows to be a `char*`.

uxn is big-endian, so it'll be the case that, for example, `&a` is 0xfef6, and `(mem[0xfef6], mem[0xfef7]) == (0, 'H')`.

Because dereferencing a `char*` [_is_ implemented correctly](https://github.com/lynn/chibicc/blob/uxn/codegen.c#L71), you end up accessing the `0`, not the `'H'`.

**Comment by hikari-no-yume** [comment]
As of 8224195e5332eaf96ee3609c5013a58fe833303a, the chibicc tests (modified for uxn) halt here:

```
sub_char(7, 3, 3)
did not match expected =>
0001
instead got
0000
Run: Ended.
```

`sub_char` is defined like this, so presumably it's this bug that causes the test to fail:

```c
int sub_char(char a, char b, char c) {
  return a - b - c;
}
```
