### ISSUE TITLE
Support `asm()`

### ISSUE THREAD

**Issue by lynn** [lynn/chibicc#19]
It would be nice to support inline Uxntal, something like:

```c
int max(int x, int y) {
    return asm(x, y, "LTH2k JMP SWP2 NIP2");
}
```

The syntax I'm picturing is: _n_ values to push, followed by a literal string of Uxntal that leaves an `int` result on the stack.

Or maybe something top-level like this is even easier to implement, and more flexible in a way:

```c
int max(int x, int y);
asm("@max_ LTH2k JMP SWP2 NIP2 JMP2r");
```

**Comment by neauoire** [comment]
That's a good idea, I would make use of this! I think the nested version is a bit more clear.
