### ISSUE TITLE
Official releases of uxnasm won't assemble the cc output right now

### ISSUE THREAD

**Issue by hikari-no-yume** [lynn/chibicc#5]
The version of `uxnasm` included in the macOS binary release at https://100r.co/site/uxn.html doesn't accept the output from this compiler right now:

```
$ gcc -I. -P -E examples/day3.c -o tmp.c
$ ./chibicc tmp.c > c.tal
$ uxnasm c.tal c.rom
Unknown token: main
Unknown token: main
Assembly: Failed to assemble rom.
$
```

lynn says it's because a bare token like `main` being a function call is a newish feature. It works when building the latest `uxnasm` from source (`git clone https://git.sr.ht/~rabbits/uxn && cd uxn && ./build.sh`).

I guess many other people might have one of these binary releases, so we might want to change the emitted function calls to work the old way.

**Comment by lynn** [comment]
For reference the "immediate rune" shortcuts that were introduced into uxnasm just 4-5 months ago are…

* `;func JSR2` becomes `func`
* `;label JMP2` becomes `!label`
* `;label JCN2` becomes `?label`

The old forms each assemble into 4 bytes (LIT2 + address + opcode), the new forms into 3 bytes (opcode + address).

**Comment by neauoire** [comment]
The old builds have been updated and should include a uxnasm that supports immediate words. No need to support the old forms. Even the self-hosted assembler(drifblim) that I use supports them.

**Comment by lynn** [comment]
Thanks, @neauoire! I think that nicely addresses this.
